[package]
name = "vid_converter"
version = "0.1.0"
edition = "2021"

[dependencies]
# gstreamer = "0.21.0" # this is stupidly overcomplicated so I'll add that later trust
image = "0.24.1"
sha2 = "0.10.7"
