[package]
name = "vid_converter"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.24.7"
ffmpeg = { package = "ffmpeg-next", version = "6.0.0"}
rayon = "1.8.0"

[features]
simd_if_available = []
default = ["simd_if_available"]